@extends('layout.home')
@section('title')
    Xizmatlar
@endsection
@section('content')
    @include('site.sections.pageHeader')
    @include('site.sections.service')
    @include('site.sections.appointment')
@endsection
